version: '3.9'

services:
  postgres:
    image: postgres:alpine
    networks:
      - postgres
    volumes:
      - ./data/postgres:/data/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo-nestjs
    ports:
      - 5432:5432

  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4005:3000'
    depends_on:
      - postgres
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
