name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
            node-version: 16
      - name: Install Dependencies
        run: yarn
      
      - name: Run Test
        run: yarn test
  
  deploy:
    runs-on: self-hosted

    strategy:
        matrix:
            node-version: [16.x]
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
              node-version: ${{ matrix.node-version }}
        - run: rm -rf node_modules
        - run: npm install
        - run: cp /home/azureuser/.env .env
        - run: sudo docker compose stop && sudo docker compose up --build -d
        - run: sudo docker exec nestjs-api yarn migration:run

      
